micronaut:
  application:
    name: did-server-helper
  server:
    port: 8080
    context-path: /
# jwks:
  # key-id: did-server-key-01
  # algorithm: ES256
  # private-key-path: ./certs/private-key.pem
logger:
  levels:
    io.micronaut: INFO
