name: Deploy Native Docker Image (Latest)

on:
  workflow_run:
    workflows: ["Java CI: Code Quality, Formatting, and Tests"]
    types:
      - completed
    branches: [ "main", "master" ]

jobs:
  build-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup JDK 21 and Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: ğŸ”‘ Configure Docker Registry Credentials
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_HOST }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ—ï¸ Build Image and Push Docker (Latest Tag)
        run: mvn clean install -DskipTests -Pdocker -Dimage.tag=latest